translate nodeshape
cytoscape/cytoscape-web pull request #247
Opened 2024-08-30 23:31 UTC by GAOChengzhan

Jira: [CW-302](https://cytoscape.atlassian.net/browse/CW-302)
`Parallelogram` does not in exist _cytoscape.js_. Instead, it only exists `rhomboid` in _cytoscape.js_.  Therefore, I updated the convertor so that both 'parallelogram' and 'rhomboid' in cx2 are mapped to 'rhomboid' and it can be rendered correctly.

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/4c4347d6-cabf-42e4-ac09-dc55f774d7b4">

2024-09-03 13:33 UTC, d2fong requested changes
This approach brings up some issues related to round tripping between cytoscape desktop. i.e. is it okay if the user imports cx2 with `parallelogram` values and then it exports back out to `rhomboid`?   

Another approach that keeps doesnt convert values is to just change the renderer to render `rhomboid` when value `parallelogram` is given.  We could talk about it in the meeting today.  

See here for an example renderring different shapes:
https://github.com/cytoscape/cytoscape-web/blob/development/src/components/NetworkPanel/CyjsRenderer/cyjs-util.ts#L235

2024-09-03 19:47 UTC, GAOChengzhan commented
> This approach brings up some issues related to round tripping between cytoscape desktop. i.e. is it okay if the user imports cx2 with `parallelogram` values and then it exports back out to `rhomboid`?
> 
> Another approach that doesnt convert values is to just change the renderer to render `rhomboid` when value `parallelogram` is given. We could talk about it in the meeting today.
> 
> See here for an example renderring different shapes: https://github.com/cytoscape/cytoscape-web/blob/development/src/components/NetworkPanel/CyjsRenderer/cyjs-util.ts#L235

Okay, got it. Let me update the code

2024-09-03 23:58 UTC, GAOChengzhan commented on src/components/NetworkPanel/CyjsRenderer/cyjs-factory.ts
> +      ),
@d2fong Hi Dylan, I move the translate function here before giving the data to cytoscape.js.

2024-09-03 23:59 UTC, GAOChengzhan commented on src/components/NetworkPanel/CyjsRenderer/cyjs-util.ts
> +            obj.data(key, NodeShapeMapping[value as NodeShapeType])
And also here

2024-09-04 14:55 UTC, d2fong commented
Ok looks good.

2024-09-04 14:55 UTC, d2fong approved these changes

2024-09-04 14:55 UTC, merged